[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_seal_whitelist = "5E7FfNPZjzbxLJCTz64oTsk1ZpKZKDsqAiG5H3igxe9x"
solana_seal_account_based = "8G4ruxnreCskTDTHN43PtKsU7oBzW3ReZEpLcsfeHDmp"
solana_seal_starter = "HMyQGJVyXw5MvpHbKQ8noKXcbtX9TyPkwM8TcyHSFdTJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
